title: Eazify.net
description: This is a personal URL shortener by Dmitry Soshnikov
logo: /assets/img/logo.png
show_downloads: false
google_analytics: UA-37948729-2
yandex_metrika: 67488091
theme: jekyll-theme-minimal
permalink: /:slug/
repository: shwars/eazify
plugins:
  - jekyll-redirect-from

#repository: shwars/eazify
